---
stages:
  - prepare
  - build
  - deploy

get-image-tag:
  stage: prepare
  image:
    name: bitnami/git
    entrypoint: ["bash"]
  script:
    - set -e
    - 'echo "CI triggered by: $CI_PIPELINE_SOURCE"'
    - echo "APP_VERSION_TAG=$(git describe --tags --always HEAD | sed -n -E 's/^([0-9\.]+)(-([0-9]+.*))?/\1-enote-\3/p')" > docker-variables.env
    - cat docker-variables.env
  artifacts:
    reports:
      dotenv: docker-variables.env

build-and-push-image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - |
      set -e
      mkdir -p /kaniko/.docker
      echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
      /kaniko/executor --context $CI_PROJECT_DIR --dockerfile Dockerfile --destination $CI_REGISTRY_IMAGE:$TAG
  variables:
    TAG: $APP_VERSION_TAG

.update-helm-charts-template:
  stage: deploy
  trigger:
    project: 'sre/helm-charts'
    strategy: depend
    forward:
      pipeline_variables: true

update-helm-charts-dev:
  extends: .update-helm-charts-template
  variables:
    ENV: dev
    APP: sync-storage
    TAG: $APP_VERSION_TAG
  rules:
  - if: >-
      $CI_PIPELINE_SOURCE != "schedule"
      && $CI_COMMIT_REF_NAME != $CI_COMMIT_TAG
      && $CI_COMMIT_REF_NAME == "enote"
